export function recommendNext(stats) { const list = Object.entries(stats.games || {}).map(([game, v]) => ({ game, ...v, avg: v.totalScore / Math.max(1, v.plays) })); list.sort((a, b) => a.plays - b.plays || a.avg - b.avg); return list[0]?.game || 'family-match' }
export function difficultyFor(gameStats) { const avg = gameStats?.avg ?? 0; if (avg < 40) return 'easy'; if (avg < 75) return 'medium'; return 'hard' }
export function getSupportPlan(assessment) {
	if (!assessment?.enoughData) return { band: 'not-enough-data', title: 'Keep building a gentle routine', reason: 'CARE needs at least four shared activities before it can describe a pattern. This is not a memory or dementia assessment.', nextStep: 'Try one familiar activity with a caregiver and check in again later.', carePath: 'CARE daily support' };
	const hard = assessment.feelings?.hard || 0; const enjoyed = assessment.feelings?.enjoyed || 0;
	if (hard > enjoyed) return { band: 'gentler-support', title: 'Try a gentler shared session', reason: 'Recent activities were more often described as difficult than enjoyable.', nextStep: 'Choose a familiar game, use two choices, add hints, or invite a trusted caregiver to join.', carePath: 'CARE caregiver-supported plan' };
	if ((assessment.averageMinutes || 0) >= 25) return { band: 'rest-breaks', title: 'Add comfortable rest breaks', reason: `Recent sessions averaged about ${assessment.averageMinutes} minutes. Longer sessions can be tiring, so time is used here only to shape a gentler routine.`, nextStep: 'Try 10–20 minute sessions with a drink, conversation, or rest between activities.', carePath: 'CARE paced activity plan' };
	if (assessment.activeDays < 2) return { band: 'caregiver-follow-up', title: 'Invite a caring check-in', reason: 'There have been fewer active days recently, so a little companionship may help the routine feel easier.', nextStep: 'Ask a trusted person to share a short memory moment or conversation this week.', carePath: 'CARE connection plan' };
	return { band: 'steady-support', title: 'Continue the familiar routine', reason: 'Recent activities were mostly comfortable or positive, with a continuing local routine.', nextStep: 'Keep choosing familiar activities and stop whenever the person feels tired.', carePath: 'CARE everyday support' };
}
