import React, { useEffect, useMemo, useRef, useState } from 'react';
import { saveSession, logEvent } from '../db/db';
import { GAME_DATA, PEOPLE, CULTURE, LIFE_INTERESTS, PLACES } from './data';
import { speakText } from '../services/speech';

function shuffle(items) { return [...items].sort(() => Math.random() - .5) }
function say(text, language) { return speakText(text, language) }
export default function Game({ gameId, profile, onDone, onBack }) {
  const meta = GAME_DATA[gameId];
  const startedAt = useRef(Date.now());
  const [round, setRound] = useState(0); const [score, setScore] = useState(0); const [correct, setCorrect] = useState(0); const [chosen, setChosen] = useState(null); const [hint, setHint] = useState(false); const [finished, setFinished] = useState(false); const [feedback, setFeedback] = useState(''); const [speechStatus, setSpeechStatus] = useState(''); const [companion, setCompanion] = useState(false);
  const choiceCount = localStorage.getItem('CARE_COMFORT_MODE') === 'true' ? 2 : 4;
  const question = useMemo(() => makeQuestion(gameId, round, profile, choiceCount), [gameId, round, profile.favoritePerson, profile.region, choiceCount]);
  useEffect(() => { logEvent(profile.id, 'game_start', { gameId }) }, [gameId, profile.id]);

  function answer(value) {
    if (chosen !== null) return;
    const isCorrect = value === question.answer; const nextScore = score + (isCorrect ? 20 : 0); const nextCorrect = correct + Number(isCorrect);
    setChosen(value); setScore(nextScore); setCorrect(nextCorrect); setFeedback(isCorrect ? 'Lovely choice. Let’s continue together.' : 'That is okay. This is practice, not a test.');
    logEvent(profile.id, 'answer', { gameId, round, correct: isCorrect, usedHint: hint });
    window.setTimeout(() => {
      if (round + 1 >= meta.rounds) { saveSession({ profileId: profile.id, gameId, score: nextScore, correct: nextCorrect, rounds: meta.rounds, hintsUsed: Number(hint), durationSeconds: Math.max(1, Math.round((Date.now() - startedAt.current) / 1000)) }); setFinished(true) } else { setRound(value => value + 1); setChosen(null); setHint(false); setFeedback('') }
    }, 1250);
  }

  if (finished) return <section className="card elder-card p-8 text-center max-w-2xl mx-auto"><div className="text-6xl" aria-hidden="true">🌟</div><h2 className="text-3xl font-black mt-4">Thank you for spending time with CARE</h2><p className="text-lg text-slate-600 mt-3">You completed {meta.rounds} gentle memory moments. There is no pass or fail.</p><div className="mt-7"><p className="font-bold text-lg">How did this feel today?</p><div className="grid grid-cols-3 gap-3 mt-3"><button className="game-choice bg-rose-50" onClick={() => { logEvent(profile.id, 'game_feedback', { gameId, feeling: 'hard' }); onDone(score) }}>A little hard</button><button className="game-choice bg-amber-50" onClick={() => { logEvent(profile.id, 'game_feedback', { gameId, feeling: 'okay' }); onDone(score) }}>It was okay</button><button className="game-choice bg-emerald-50" onClick={() => { logEvent(profile.id, 'game_feedback', { gameId, feeling: 'enjoyed' }); onDone(score) }}>I enjoyed it</button></div></div><button className="btn btn-soft elder-action mt-6" onClick={() => onDone(score)}>Back to activities</button></section>;

  return <main className="card elder-card p-6 sm:p-8 max-w-2xl mx-auto"><button onClick={onBack} className="text-lg font-bold text-teal-800">← Back to activities</button><header className="mt-5 flex justify-between items-start gap-4"><div><div className="text-5xl" aria-hidden="true">{meta.icon}</div><h1 className="text-3xl font-black mt-3">{meta.title}</h1><p className="text-slate-600 mt-2">One small step at a time. Take as long as you need.</p></div><div className="rounded-xl bg-teal-50 px-4 py-2 font-bold text-teal-900">{round + 1} of {meta.rounds}</div></header><button className="btn btn-soft elder-action mt-5" onClick={() => setCompanion(value => !value)} aria-pressed={companion}>👥 {companion ? 'Playing together' : 'Play with a family member'}</button>{companion && <p className="companion-note mt-4"><b>Companion tip:</b> Read one sentence slowly, wait for a response, and use a hint only if it helps. Celebrate the conversation, not the answer.</p>}<section className="mt-5 rounded-2xl bg-amber-50 border-2 border-amber-100 p-5"><p className="text-xl font-bold leading-snug">{question.prompt}</p><div className="flex flex-wrap gap-3 mt-4"><button onClick={() => say(question.prompt, profile.language)} className="btn btn-soft elder-action">🔊 Hear the question</button>{question.voice && <button onClick={() => say(question.voice, profile.language)} className="btn btn-soft elder-action">🔊 Hear it again</button>}</div>{hint && <p className="mt-4 text-lg text-teal-900"><b>A small hint:</b> {question.hint}</p>}</section><div className="grid sm:grid-cols-2 gap-4 mt-6">{question.options.map(option => <button key={option} onClick={() => answer(option)} disabled={chosen !== null} className={`game-choice text-left ${chosen !== null && option === question.answer ? 'bg-emerald-100 border-emerald-600' : chosen === option ? 'bg-amber-100 border-amber-500' : 'bg-white'}`}>{option}</button>)}</div>{chosen === null && <button className="btn btn-soft elder-action mt-5" onClick={() => { setHint(true); logEvent(profile.id, 'game_hint', { gameId, round }) }}>💡 Show a small hint</button>}{feedback && <p className="voice-status mt-5" role="status">{feedback}</p>}<p className="text-base text-slate-500 mt-6">CARE records activity completion and your feedback only. It does not diagnose memory problems.</p></main>
}

function makeQuestion(id, round, profile, choiceCount) {
  if (id === 'family-match') { const person = profile.favoritePerson?.trim() || PEOPLE[round % PEOPLE.length]; const options = shuffle([person, ...PEOPLE.filter(value => value !== person).slice(0, choiceCount - 1)]); return { prompt: 'Which familiar person would you like to think about today?', options, answer: person, hint: person === profile.favoritePerson?.trim() ? 'This is the special person you named when setting up CARE.' : 'Think of a close family member.' } }
  if (id === 'culture-memory') { const matching = CULTURE.find(([region]) => region === profile.region) || CULTURE[round % CULTURE.length]; const [region, festival] = matching; const options = shuffle([festival, ...CULTURE.map(([, value]) => value).filter(value => value !== festival).slice(0, choiceCount - 1)]); return { prompt: `Which celebration is connected with ${region}?`, options, answer: festival, hint: `It is a familiar celebration from ${region}.` } }
  if (id === 'name-place') { const place = PLACES[round % PLACES.length]; return { prompt: 'Which of these is a place in Northeast India?', options: shuffle([place, 'Jaipur', 'Pune', 'Surat'].slice(0, choiceCount)), answer: place, hint: 'Think of places close to the hills, valleys, and rivers of the Northeast.' } }
  if (id === 'everyday-skills') { const selected = profile.activities?.length ? profile.activities : LIFE_INTERESTS.map(item => item.id); const questions = [
    { category: 'farm', prompt: 'What might you carry seeds or vegetables in?', answer: 'A basket', options: ['A basket', 'A pillow', 'A comb', 'A slipper'], hint: 'Think of something useful for the field or garden.' },
    { category: 'food', prompt: 'What might you take when going to buy vegetables?', answer: 'A shopping bag', options: ['A shopping bag', 'A blanket', 'A toothbrush', 'A book'], hint: 'Think of carrying fresh food home.' },
    { category: 'craft', prompt: 'What can be used to make a woven cloth?', answer: 'Thread', options: ['Thread', 'Soap', 'A plate', 'A key'], hint: 'Think of a loom, needle, or handwork.' },
    { category: 'music', prompt: 'What can bring people together at a celebration?', answer: 'A familiar song', options: ['A familiar song', 'A traffic signal', 'A password', 'A receipt'], hint: 'Think of voices, rhythm, and sharing.' },
    { category: 'family', prompt: 'What can make a family visit feel warm?', answer: 'Talking together', options: ['Talking together', 'Rushing away', 'A locked door', 'A silent phone'], hint: 'Think of connection and sharing memories.' },
    { category: 'work', prompt: 'What helps when arranging items for a small shop or home?', answer: 'Sorting them together', options: ['Sorting them together', 'Hiding them', 'Throwing them away', 'Turning off the light'], hint: 'Think of putting similar things in a simple order.' }
  ]; const relevant = questions.filter(question => selected.includes(question.category)); const question = (relevant.length ? relevant : questions)[round % (relevant.length || questions.length)]; return { ...question, options: shuffle(question.options.slice(0, choiceCount)) } }
  if (id === 'sequence-story') { const routines = [['Wake up', 'Have breakfast', 'Take a walk', 'Rest'], ['Prepare tea', 'Greet family', 'Talk about the day', 'Sleep']]; const routine = routines[round % routines.length]; return { prompt: 'What usually comes first in this familiar day?', options: shuffle(routine.slice(0, choiceCount)), answer: routine[0], hint: 'Think about the beginning of the day or visit.' } }
  if (id === 'local-greetings') { const greetings = [
    { language: 'as-IN', name: 'Assamese', phrase: 'নমস্কাৰ', sound: 'Nomoskar' },
    { language: 'mni-IN', name: 'Manipuri', phrase: 'খুরুমজারি', sound: 'Khurumjari' },
    { language: 'brx-IN', name: 'Bodo', phrase: 'खुलुमबाई', sound: 'Khulumbai' },
    { language: 'ne-IN', name: 'Nepali', phrase: 'नमस्ते', sound: 'Namaste' },
    { language: 'en-IN', name: 'English', phrase: 'Good morning', sound: 'Good morning' }
  ]; const preferred = greetings.find(item => item.language === profile.language) || greetings.find(item => item.language === 'en-IN'); const current = greetings[(greetings.indexOf(preferred) + round) % greetings.length]; const options = shuffle([current.sound, ...greetings.filter(item => item.sound !== current.sound).map(item => item.sound).slice(0, choiceCount - 1)]); return { prompt: `Which warm greeting is shown in ${current.name}?`, options, answer: current.sound, hint: `${current.phrase} is written in the local script.`, voice: current.sound } }
  if (id === 'festival-treasures') { const treasures = {
    Assam: ['Bihu', 'pepa'], Manipur: ['Lai Haraoba', 'pena'], Meghalaya: ['Wangala', 'drum'], Nagaland: ['Hornbill Festival', 'shawl'], Mizoram: ['Chapchar Kut', 'bamboo'], Tripura: ['Garia Puja', 'drum'], 'Arunachal Pradesh': ['Losar', 'prayer flag'], Sikkim: ['Pang Lhabsol', 'prayer flag']
  }; const [festival, object] = treasures[profile.region] || treasures.Assam; const pairs = [['Bihu', 'pepa'], ['Lai Haraoba', 'pena'], ['Wangala', 'drum'], ['Hornbill Festival', 'shawl'], ['Chapchar Kut', 'bamboo'], ['Garia Puja', 'drum'], ['Losar', 'prayer flag'], ['Pang Lhabsol', 'prayer flag']]; const current = pairs[(pairs.findIndex(pair => pair[0] === festival) + round + pairs.length) % pairs.length]; const options = shuffle([current[1], ...pairs.filter(pair => pair[1] !== current[1]).map(pair => pair[1]).slice(0, choiceCount - 1)]); return { prompt: `Which familiar item can be connected with ${current[0]}?`, options, answer: current[1], hint: `Think about music, craft, clothing, or ceremony from ${current[0]}.` } }
  if (id === 'market-memory') { const foods = { Assam: ['pitha', 'tea leaves', 'bamboo shoot', 'mustard greens'], Manipur: ['black rice', 'eromba', 'lotus stem', 'mustard greens'], Meghalaya: ['rice', 'black sesame', 'bamboo shoot', 'pineapple'], Nagaland: ['smoked chilli', 'bamboo shoot', 'rice', 'beans'], Mizoram: ['bai', 'rice', 'bamboo shoot', 'greens'], Tripura: ['berma', 'rice', 'pineapple', 'bamboo shoot'], 'Arunachal Pradesh': ['thukpa', 'rice', 'buckwheat', 'bamboo shoot'], Sikkim: ['momos', 'cardamom', 'buckwheat', 'tea leaves'] }; const items = foods[profile.region] || foods.Assam; const answer = items[round % items.length]; const options = shuffle([answer, ...['apple', 'bread', 'pasta', 'cereal'].slice(0, choiceCount - 1)]); return { prompt: `Which item might you recognise at a ${profile.region} market?`, options, answer, hint: 'Think of a familiar ingredient, snack, or crop from home.' } }
  const phrases = ['Namaskar', 'Good morning', 'How are you?', 'See you tomorrow']; const phrase = phrases[round % phrases.length]; return { prompt: 'Listen to the friendly phrase, then choose what you heard.', options: shuffle([phrase, ...phrases.filter(value => value !== phrase).slice(0, choiceCount - 1)]), answer: phrase, hint: 'Press “Hear it again” as often as you need.', voice: phrase };
}
